version: '3.8'

services:
    php-api:
        build:
            context: ./docker
        container_name: php-api
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        tty: true
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "8081:8000"
        command: >
            sh -c "composer install &&
                   composer dump-autoload &&
                   touch database/database.sqlite &&
                   php artisan migrate &&
                   php artisan serve --host=0.0.0.0 --port=8000"
